python3 train.py --config=configs/resnet50.yml \
                 --num_epochs=60 \
                 --batch_size=32 \
                 --image_size=256 \
                 --loss=cross_entropy \
                 --optim_lr=0.0003 \
                 --optim_wd=0 \
                 --num_grad_acc=0 \
                 --ls=true \
                 --bestfitting=true \
                 --scheduler=step \
                 --step_size=40

python3 train.py --config=configs/resnet50.yml \
                 --num_epochs=60 \
                 --batch_size=32 \
                 --image_size=256 \
                 --loss=cross_entropy \
                 --optim_lr=0.0005 \
                 --optim_wd=0 \
                 --num_grad_acc=0 \
                 --ls=true \
                 --bestfitting=true \
                 --scheduler=step \
                 --step_size=40

python3 train.py --config=configs/resnet50.yml \
                 --num_epochs=60 \
                 --batch_size=32 \
                 --image_size=256 \
                 --loss=cross_entropy \
                 --optim_lr=0.0007 \
                 --optim_wd=0 \
                 --num_grad_acc=0 \
                 --ls=true \
                 --bestfitting=true \
                 --scheduler=step \
                 --step_size=40

python3 train.py --config=configs/resnet50.yml \
                 --num_epochs=60 \
                 --batch_size=32 \
                 --image_size=256 \
                 --loss=cross_entropy \
                 --optim_lr=0.0009 \
                 --optim_wd=0 \
                 --num_grad_acc=0 \
                 --ls=true \
                 --bestfitting=true \
                 --scheduler=step \
                 --step_size=40

python3 train.py --config=configs/resnet50.yml \
                 --num_epochs=60 \
                 --batch_size=32 \
                 --image_size=256 \
                 --loss=cross_entropy \
                 --optim_lr=0.001 \
                 --optim_wd=0 \
                 --num_grad_acc=0 \
                 --ls=true \
                 --bestfitting=true \
                 --scheduler=step \
                 --step_size=40
