setup:
  stage: True # False takes in all cells
  cell_type: 3
  version: 'densenet121'
  run_test: True 
  project: 'recursion-densenet'

submission:
  pattern: 'cosface'

data:
  train: 'train.csv'

model:
  image_size: 256
  num_classes: 1108
  arch: 'densenet121'
  
train:
  batch_size: 16
  num_epochs: 30
  
val:
  batch_size: 32

test:
  batch_size: 32
  
loss:
  name: 'cross_entropy' # arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, cross_entropy, normsoftmax
  
optimizer:
  name: 'radam'
  params:
    lr: 0.0003

scheduler:
  name: 'cosine'
  params:
    eta_min: 0.00003
    T_max: 276