setup:
  cell_type: 0
  stage: 1  # 'stage 0: small validation set;' 
            # 'stage 1: last batch as validation;'
  version: 'original_cosface' 
  find_lr: True

data:
  name: 'RCICDefaultDataset'
  train: 'train.csv'

model:
  image_size: 256
  num_classes: 1108 # 512 for amsoftmax
  arch: 'densenet121'
  
train:
  batch_size: 24 # 192 for 384; 320 for 224; 128 for 512
  num_epochs: 30
  log_freq: 50
  
val:
  batch_size: 32
  log_freq: 50

test:
  batch_size: 32
  
loss:
  name: 'cosface' # arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, cross_entropy, 
  params: 
    gamma: 2 # focal
    in_features: 512 
    out_features: 1108 

optimizer:
  name: 'adam' # sgd, adam
  params:
    lr: 0.0003 # 3e-4

scheduler:
  name: 'cosine' # exponential, cosine
  params:
    # gamma: 0.95
    eta_min: 0.00003
    T_max: 184
    # base_lr: 0.0003 
    # max_lr: 0.001 
    # step_size_up: 50