setup:
  stage: True # False takes in all cells
  cell_type: 3
  version: 'densenet201-512'
  run_test: False 

submission:
  pattern: 'cosface-dn201'

data:
  train: 'train.csv'

model:
  image_size: 512
  num_classes: 1108
  arch: 'densenet201'
  
train:
  batch_size: 32
  num_epochs: 1
  
val:
  batch_size: 96

test:
  batch_size: 96
  
loss:
  name: 'cosface' # arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, cross_entropy, normsoftmax
  
optimizer:
  name: 'adamw'
  params:
    lr: 0.0003

scheduler:
  name: 'cosine'
  params:
    eta_min: 0.00003
    T_max: 92
