setup:
  stage: True # False takes in all cells
  cell_type: 3
  version: 'efficientnet-b0'
  run_test: False

submission:
  pattern: 'efficientnet-b0'

data:
  train: 'train.csv' # 'U2OS_train_small.csv'

model:
  image_size: 320
  num_classes: 1108
  arch: 'efficientnet-b0'
  antialias: False
  
train:
  batch_size: 48
  num_epochs: 60
  
val:
  batch_size: 96

test:
  batch_size: 96
  
loss: 
  name: 'cross_entropy' # arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, cross_entropy, normsoftmax
  params:
    in_features: 512
  
optimizer:
  name: 'radam' 
  params:
    lr: 0.0005
    weight_decay: 0.0

scheduler:
  name: 'look_ahead' # cosine
  params:
    k: 10
    # eta_min: 0.00003
    # T_max: 276
    # step_size: 30