setup:
  use_cuda: False
  cell_type: 3
  stage: 1 # 'stage 0: no validation set;' 
           # 'stage 1: last batch as validation;'
           # 'stage 2: proper training' 
  version: 'first_attempt'

data:
  name: 'RCICDefaultDataset'

model:
  name: 'resnet18'
  arch: 'resnet18'

train:
  dir: 'results'
  batch_size: 48
  num_epochs: 2

loss:
  name: 'cross_entropy'

optimizer:
  name: 'adam'
  params:
    lr: 0.0003

scheduler:
  name: 'exponential'