setup:
  stage: 2  # 'stage 0: small validation set;' 
            # 'stage 1: last batch as validation;'
  plate: 1 # 1,2,3,4
  cell_type: 3
  version: 'resnet18_plate1' 

# find_lr:
#   run: False
#   end_lr: 1
#   num_iter: 20
#   step_mode: 'linear'

data:
  name: 'RCICDefaultDataset'
  train: 'train.csv' # U2OS_train_small

model:
  image_size: 320
  num_classes: 277 # 512 for amsoftmax
  arch: 'resnet18'
  
train:
  batch_size: 48 # 192 for 384; 320 for 224; 128 for 512
  num_epochs: 50
  log_freq: 50
  
val:
  batch_size: 96
  log_freq: 50

test:
  batch_size: 96
  
loss:
  name: 'cross_entropy' # cross_entropy, arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, 
  params: 
    gamma: 2 # focal
    in_features: 512 
    out_features: 277 

optimizer:
  name: 'adamw' # sgd, adam
  params:
    lr: 0.0003 # 3e-4

scheduler:
  name: 'cosine' # exponential, cosine
  params:
    # gamma: 0.95
    eta_min: 0.00003
    T_max: 334 # 34
    # base_lr: 0.0003 
    # max_lr: 0.001 
    # step_size_up: 50