setup:
  use_cuda: False
  cell_type: -1
  stage: 1 # 'stage 0: no validation set;' 
           # 'stage 1: last batch as validation;'
           # 'stage 2: proper training' 
  combine: True
  version: 'first_attempt'
  use_small: False
  test_size: 0.1

data:
  name: 'RCICDefaultDataset'

model:
  name: 'resnet34'
  arch: 'resnet34'

train:
  dir: './results'
  batch_size: 16
  num_epochs: 2

loss:
  name: 'cross_entropy'

optimizer:
  name: 'adam'
  params:
    lr: 0.0003
    weight_decay: 0.01

scheduler:
  name: 'exponential'

