setup:
  cell_type: 3
  stage: 1 # 'stage 0: no validation set;' 
           # 'stage 1: last batch as validation;'
           # 'stage 2: proper training' 
  version: 'bf_arcface' # 'train.csv'

data:
  name: 'RCICDefaultDataset'
  train: 'U2OS_train.csv'

model:
  image_size: 224
  arch: 'resnet34'
  name: 'resnet34'
  pool: 'GeM' # 'SPoC', 'MAC', 'RMAC', 'GeM', 'Rpool', 'Flatten', 'CompactBilinearPooling'
  loss_module: 'cosface' # 'arcface', 'cosface', 'adacos', 'softmax'
  use_fc: True
  fc_dim: 512
  dropout: 0.25
  s: 30.0

train:
  batch_size: 128
  num_epochs: 30
  # num_grad_acc: None
  
val:
  batch_size: 128 # * num gpus

test:
  batch_size: 128 # * num gpus
  
loss:
  name: 'cosface' # 'arcface', 'cosface', 'adacos', 'softmax', 'sphere' 

optimizer:
  name: 'adam'
  params:
    lr: 0.003 # 3e-4

scheduler:
  name: 'cosine' # exponential
  params:
    eta_min: 0.00003
    T_max: 34
