setup:
  cell_type: 3
  stage: 0 # 'stage 0: small validation set;' 
           # 'stage 1: last batch as validation;'
           # 'stage 2: proper training' 
  version: 'train_full_s0' # s fot stage

data:
  name: 'RCICDefaultDataset'
  train: 'train.csv'

model:
  image_size: 512
  arch: 'resnet34'
  name: 'resnet34'
  pool: 'GeM' # 'SPoC', 'MAC', 'RMAC', 'GeM', 'Rpool', 'Flatten', 'CompactBilinearPooling'
  loss_module: 'arcface' # 'arcface', 'cosface', 'adacos', 'softmax'
  use_fc: True
  fc_dim: 512
  dropout: 0.25
  s: 30.0

train:
  batch_size: 128
  num_epochs: 10
  # num_grad_acc: None
  
val:
  batch_size: 128 # * num gpus

test:
  batch_size: 128 # * num gpus
  
loss:
  name: 'arcface' # 'arcface', 'cosface', 'adacos', 'softmax', 'sphere' 
  # params: # only for  adacos and amsoftmax
  #   in_features: 512 
  #   out_features: 1108    

optimizer:
  name: 'adam'
  params:
    lr: 0.003 # 3e-4

scheduler:
  name: 'cosine' # exponential
  params:
    eta_min: 0.00003
    T_max: 501 # 34