setup:
  cell_type: 3
  stage: 1  # 'stage 0: small validation set;' 
            # 'stage 1: last batch as validation;'
  version: 'cos' 

data:
  name: 'RCICDefaultDataset'
  train: 'train.csv' # U2OS_train_small

model:
  image_size: 112
  num_classes: 512
  arch: 'resnet18'
  loss_module: 'arcface' # 'arcface', 'cosface', 'adacos', 'softmax'
  use_fc: True
  fc_dim: 512
  dropout: 0.25

train:
  batch_size: 16 # 192 for 384; 320 for 224; 128 for 512
  num_epochs: 50
  log_freq: 50
  
val:
  batch_size: 16 # * num gpus
  log_freq: 50

test:
  batch_size: 224 # * num gpus
  
loss:
  name: 'amsoft' # cross_entropy, focal, arcface, cosface, adacos, amsoft
  params: # only for  adacos and amsoftmax
    # gamma: 2
    in_features: 512 
    out_features: 1108

optimizer:
  name: adam # sgd, adam
  params:
    lr: 0.001 # 3e-4

scheduler:
  name: 'cosine' # exponential, cosine
  params:
    eta_min: 0.00003
    T_max: 256 # 34
    # base_lr: 0.0003 
    # max_lr: 0.001 
    # step_size_up: 50