setup:
  stage: True # False takes in all cells
  cell_type: 3
  version: 'resnet18-step'
  run_test: False

submission:
  pattern: 'cosface'

data:
  train: 'train.csv' # 'U2OS_train_small.csv'

model:
  image_size: 320
  num_classes: 1108
  arch: 'resnet18'
  
train:
  batch_size: 48
  num_epochs: 60
  
val:
  batch_size: 96

test:
  batch_size: 96
  
loss: 
  name: 'cross_entropy' # arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, cross_entropy, normsoftmax
  params:
    in_features: 1024
  
optimizer:
  name: 'radam' # look_ahead
  params:
    lr: 0.0005
    weight_decay: 0.01

scheduler:
  name: 'step' # cosine
  params:
    # eta_min: 0.00003
    # T_max: 276
    step_size: 30