setup:
  stage: True # False takes in all cells
  cell_type: 3
  version: 'resnet34_normsoftmax'
  run_test: True 

submission:
  pattern: 'cosface'

data:
  train: 'train.csv'

model:
  image_size: 320
  num_classes: 1108
  arch: 'resnet34'
  
train:
  batch_size: 32
  num_epochs: 30
  
val:
  batch_size: 48

test:
  batch_size: 48
  
loss:
  name: 'normsoftmax' # arcface, cosface, adacos, sphereface, amsoftmax, focal, ls_cross_entropy, cross_entropy, normsoftmax
  
optimizer:
  name: 'adamw'
  params:
    lr: 0.0003

scheduler:
  name: 'cosine'
  params:
    eta_min: 0.00003
    T_max: 276    