setup:
  cell_type: 3
  stage: 1 # 'stage 0: no validation set;' 
           # 'stage 1: last batch as validation;'
           # 'stage 2: proper training' 
  version: 'USO2_ft_drop025_e100' # 'train.csv'
  fine_tune: True

data:
  name: 'RCICDefaultDataset'
  train: 'U2OS_train.csv'

model:
  image_size: 224
  arch: 'resnet34'
  name: 'resnet34'
  pool: 'GeM' # 'SPoC', 'MAC', 'RMAC', 'GeM', 'Rpool', 'Flatten', 'CompactBilinearPooling'
  loss_module: 'softmax' # 'arcface', 'cosface', 'softmax'  
  use_fc: True
  dropout: 0.25
  s: 30.0

train:
  batch_size: 128
  num_epochs: 100 # 50
  # num_grad_acc: None
  
val:
  batch_size: 128 # * num gpus

test:
  batch_size: 128 # * num gpus
  
loss:
  name: 'cross_entropy'

optimizer:
  name: 'adam'
  params:
    lr: 0.0003

scheduler:
  name: 'cosine' # exponential
  params:
    eta_min: 0.00003
    T_max: 34
