setup:
  cell_type: 3
  stage: -1 # 'stage -1: no validation'
            # 'stage 0: small validation set;' 
            # 'stage 1: last batch as validation;'
            # 'stage 2: proper training' 
  version: '4g_t0123' # s fot stage

data:
  name: 'RCICDefaultDataset'
  train: 'train.csv'

model:
  image_size: 112
  arch: 'resnet18'
  name: 'resnet18'
  pool: 'GeM' # 'SPoC', 'MAC', 'RMAC', 'GeM', 'Rpool', 'Flatten', 'CompactBilinearPooling'
  loss_module: 'softmax' # 'arcface', 'cosface', 'adacos', 'softmax'
  use_fc: True
  fc_dim: 512
  dropout: 0.25
  s: 30.0

train:
  batch_size: 240
  num_epochs: 20
  log_freq: 50
  # num_grad_acc: None
  
val:
  batch_size: 256 # * num gpus
  log_freq: 50

test:
  batch_size: 256 # * num gpus
  
loss:
  name: 'cross_entropy' # 'arcface', 'cosface', 'adacos', 'softmax', 'sphere' 
  # params: # only for  adacos and amsoftmax
  #   in_features: 512 
  #   out_features: 1108    

optimizer:
  name: 'adam'
  params:
    lr: 0.0003 # 3e-4

scheduler:
  name: 'cyclic_lr' # exponential
  params:
    step_size: 10
    max_lr: 0.001 # T_max: 256 # 34
    base_lr: 0.00003 # eta_min: 0.00003